### ISSUE TITLE
Latch tweak request

### ISSUE THREAD

**Issue by quantamrhino** [garynewby/PianoKeyboard#13]
Thanks for adding the latch feature.
can you make it so that in latch mode, the keys become more like toggle buttons? So in latch mode key 'K' is pressed, it stays pressed. But pressing it again should release it. 
Thanks!
Also, making the latch variable inspectable will help identify which state the keyboard is in for showing UI etc.
Thanks!

**Comment by garynewby** [comment]
Added in 1.0.25
