### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by sdappster** [garynewby/PianoKeyboard#14]
<img width="1026" alt="Screen Shot 2021-01-24 at 7 03 25 PM" src="https://user-images.githubusercontent.com/77844760/105657975-62b54500-5e7a-11eb-8d0d-c85c35536dba.png">

I cannot get the project to run.

**Comment by garynewby** [comment]
Make sure you have SwiftLint installed: https://github.com/realm/SwiftLint

**Comment by sdappster** [comment]
Installed SwiftLint through Cocoa Pods. Still the same error message.

**Comment by garynewby** [comment]
You'll need to install SwiftLint with Homebrew: `brew install swiftlint` to build the example.
