### ISSUE TITLE
PianoKeyboardView not showing up

### ISSUE THREAD

**Issue by yeniful** [garynewby/PianoKeyboard#19]
### Issue

I added this package via SPM on the Example app, but PianoKeyboardView did not appear. What do I need to do additionally?

---

### ScreenShot
![image](https://user-images.githubusercontent.com/77262576/232321406-6e3eee72-385c-4cc1-8cb0-019cb6e65ef0.png)

--- 
### Device / OS
iPhone 13 / iOS 16.4.1

**Comment by K1RA-16** [comment]
same problem

**Comment by K1RA-16** [comment]
you need to explicitly specify style in PianoKeyboardView

**Comment by garynewby** [comment]
Example app should be fixed now
